print("SSS")
a = input("Input your name")
print("Hello, " + a)
print("Welcome to the program!")
print("This is a simple Python script.")    
print("Thank you for using this script.")
print("Goodbye!")       
print("This is the end of the script.")
print("Have a great day!")